FROM ubuntu:24.10

ENV MATHICS3_HOME=/home/ubuntu

ENV MATHICS3_MODULE_OPTION="--load-module pymathics.graph,pymathics.natlang"

ENV ENTRYPOINT_COMMAND="docker run -it {MATHICS_IMAGE}"
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
WORKDIR $MATHICS3_HOME

COPY requirements.txt ./
RUN apt-get update
RUN apt-get install -qq apt-utils

# we need libsqlite3-dev now if ubuntu doesn't come with that, we'll need
# to build our own Python
# Leave out inkscape  for now.

# inxi and mesa-utils might be optional
# npm pulls in nodejs, but we'll be explicit.

RUN apt-get update -y && apt-get upgrade -y -qq

# Install lots of packages
RUN apt-get install -y -qq \
    asymptote \
    cargo \
    evince \
    gfortran \
    git \
    gyp \
    latexmk texlive-xetex \
    libffi-dev \
    liblapack-dev \
    libmysqlclient-dev \
    libopenblas-dev \
    librsvg2-bin \
    libxcb-cursor-dev \
    libxml2-dev \
    libxslt1-dev \
    llvm-15 \
    llvm-15-dev \
    lmodern texlive-latex-extra \
    maria \
    mesa-utils \
    nodejs \
    npm \
    pkg-config \
    pyqt5-dev-tools \
    python3-pip \
    python3.12-venv \
    remake \
    rustc \
    sqlite3 \
    texlive-fonts-recommended \
    tk8.6-blt2.5 \
    x11-apps \
    xserver-xorg-video-all

# # to make docker layers be more usuable in development
# # defer deletion until close to the end
# # RUN rm -fr /tmp*_amd64.deb

RUN /usr/bin/python3.12 -m venv /opt/python3.12
ENV PATH=.:/opt/python3.12/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV PYTHON=/opt/python3.12/bin/python3.12
ENV PIP=/opt/python3.12/bin/pip
RUN $PYTHON -m pip install --upgrade pip

# ################
# # Mathics core #
# ################

RUN git clone --depth 1 https://github.com/Mathics3/mathics-scanner.git
RUN (cd mathics-scanner && $PIP install -e .[full])
RUN $PIP install cython trepan3k
RUN git clone --depth 1 https://github.com/Mathics3/mathics-core.git
RUN (cd mathics-core && git submodule update --init --recursive && $PIP install -e .[full])
RUN (cd mathics-core && bash ./admin-tools/make-JSON-tables.sh)

##############################################
# Mathics Modules: Trepan, Graph, and Natlang
##############################################
RUN git clone --depth 1 https://github.com/Mathics3/Mathics3-trepan.git
RUN (cd Mathics3-trepan && $PIP install -e .)

RUN git clone --depth 1 https://github.com/Mathics3/trepan3k-mathics-debugger/
RUN (cd trepan3k-mathics-debugger && $PIP install -e .)

RUN $PIP install -e git+https://github.com/Mathics3/pymathics-graph#egg=pymathics-graph
RUN $PIP install -e git+https://github.com/Mathics3/pymathics-natlang#egg=pymathics-natlang
# # RUN $PIP install "pymathics-natlang>=8"

RUN $PIP install spacy
RUN $PYTHON -m spacy download en_core_web_md
RUN $PIP install nltk
RUN $PYTHON -m nltk.downloader wordnet omw-1.4

# # ENV DATA_DIR=/usr/src/app/mathics-core/mathics/doc/latex/
# # ENV DOCTEST_LATEX_DATA_PCL=/usr/src/app/mathics-core/mathics/doc/latex/doctext_latex_data.pcl
# # ENV DOCTEST_USER_HTML_DATA_PATH=/usr/src/app/mathics-core/mathics/doc/doc_html_data.pcl

# # COPY tex-images/*.pdf mathics-core/mathics/doc/latex/
# # ENV DOC_LATEX_FILE=/usr/src/app/mathics-core/mathics/doc/latex/documentation.tex
# # # COPY src/documentation.tex mathics-core/mathics/doc/latex/documentation.tex
# # # COPY src/version-info.tex mathics-core/mathics/doc/latex/


# # This is a mess. Figure out how to make doc.
COPY src/mathics.pdf mathics-core/mathics/doc/latex/mathics.pdf
# # RUN (cd mathics-core/mathics/doc/latex && PYTHON=$PYTHON make mathics.pdf) || /bin/true

##################
# Mathics Django #
##################
RUN git clone --depth 1 https://github.com/Mathics3/mathics-django.git
RUN (cd mathics-django && $PIP install -e .[full])
# # Get threejs version created
RUN (cd mathics-django && make build)

# # RUN $PYTHON -m pip install -e git+https://github.com/Mathics3/mathics-django#egg=Mathics-Django[full]
# # RUN $PYTHON -m pip install "Mathics-Django[full]>=6.2.0"

# # RUN (cd src/mathics-django && PIP=$PIP make)
RUN (cd mathics-django && $PYTHON mathics_django/docpipeline.py -ok --want-sorting) || true
COPY src/doc_html_data.pcl doc_html_data.pcl
RUN mkdir -p /usr/src/app/.local/var/mathics && mv -v doc_html_data.pcl /usr/src/app/.local/var/mathics/doc_data_html.pcl

##################
# Mathicsscript  #
##################

RUN git clone https://github.com/Mathics3/mathicsscript.git
RUN (cd mathicsscript && PYTHON=$PYTHON make install)

RUN ${PYTHON} -m pip install mathicsscript[full]
# RUN ${PYTHON} -m pip install -e git+https://github.com/Mathics3/mathicsscript#egg=mathicsscript[full]
# RUN (cd src/mathicsscript && make)

# ##################
# # debug stuff    #
# ##################
# RUN apt-get install -y -qq emacs
# RUN pip install trepan3k
# # RUN pip install remake

# ##################
# # Finish up      #
# ##################

# # Cleanup
# RUN rm -fr /tmp*_amd64.deb /tmp/*.whl

COPY entrypoint.sh /usr/local/bin/mathics-omnibus.sh
RUN chmod +x /usr/local/bin/mathics-omnibus.sh

EXPOSE 8000

RUN mkdir -p ${MATHICS3_HOME}/.local
RUN mkdir -p ${MATHICS3_HOME}/.config
RUN mkdir -p ${MATHICS3_HOME}/data
RUN mkdir -p ${MATHICS3_HOME}/.local/var/mathics3/Packages
COPY django-db/mathics.sqlite ${MATHICS3_HOME}/.local/var/mathics3/mathics.sqlite
RUN chown -R ubuntu:ubuntu $MATHICS3_HOME ${MATHICS3_HOME}/.local
RUN chown -R ubuntu:ubuntu ${MATHICS3_HOME}/data
USER ubuntu

ENTRYPOINT ["/usr/local/bin/mathics-omnibus.sh"]

CMD ["--help"]
