#!/bin/bash
if [ -n "$DEBUG" ]; then
    set -x
fi

# Allow customization using POSIX environment variables:
DOCKER=${DOCKER:-docker}

TAG=${TAG:-latest}
MATHICS_IMAGE=${MATHICS_IMAGE:-mathicsorg/mathics:${TAG}}

$DOCKER run -it \
  --name mathics-web \
  --rm \
  --env="DISPLAY" \
  --workdir=/app \
  --volume="$PWD":/app \
  --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
  --volume="/tmp:/usr/src/app/data" \
  $MATHICS_IMAGE \
  --mode pdf -- $@
